# Reproducer for https://github.com/quarkusio/quarkus/issues/54476
#
# Set the following in application.properties (from the issue):
quarkus.mongodb.connection-string=mongodb://%s:%s@x.y.z.w:27017/db
quarkus.mongodb.active=false
