quarkus.datasource.users.db-kind=h2
quarkus.datasource.users.jdbc.url=jdbc:h2:mem:docs-verify-users;DB_CLOSE_DELAY=-1
quarkus.datasource.users.username=sa
quarkus.datasource.users.password=sa

quarkus.hibernate-orm."users".datasource=users
quarkus.hibernate-orm."users".packages=org.acme.users
quarkus.hibernate-orm."users".schema-management.strategy=drop-and-create
